name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: misonote-markdown

# 并发控制：同一分支只运行最新的构建
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # 🆓 社区版构建 - 公开发布
  build-community:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: latest

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata for Community Edition
      id: meta-community
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch,suffix=-community-{{sha}}
          type=ref,event=pr,suffix=-community-{{sha}}
          type=semver,pattern={{version}}-community
          type=semver,pattern={{major}}.{{minor}}-community
          type=raw,value=community-latest,enable={{is_default_branch}}
          type=raw,value=latest,enable={{is_default_branch}}

    # 🚨 SECURITY: 验证企业版代码已被排除
    - name: Security Check - Verify Enterprise Code Exclusion
      run: |
        echo "🔒 验证 .dockerignore 配置..."
        if ! grep -q "enterprise/" .dockerignore; then
          echo "❌ .dockerignore 未正确配置！"
          exit 1
        fi
        echo "✅ 安全检查通过"

    - name: Build and push Community Edition
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.community
        platforms: ${{ github.event_name == 'pull_request' && 'linux/amd64' || 'linux/amd64,linux/arm64' }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta-community.outputs.tags }}
        labels: ${{ steps.meta-community.outputs.labels }}
        cache-from: |
          type=gha
          type=registry,ref=${{ env.REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:community-buildcache
        cache-to: |
          type=gha,mode=max
          type=registry,ref=${{ env.REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:community-buildcache,mode=max
        build-args: |
          BUILDKIT_INLINE_CACHE=1
          MISONOTE_EDITION=community

  # 🏢 企业版构建 - 私有发布（仅在特定条件下触发）
  build-enterprise:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, '[enterprise]')
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # 企业版需要完整的代码历史
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: latest

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 🔒 SECURITY: 验证企业版代码存在
    - name: Security Check - Verify Enterprise Code Exists
      run: |
        echo "🔒 验证企业版代码..."
        if [ ! -d "enterprise" ]; then
          echo "❌ 企业版代码目录不存在！"
          exit 1
        fi
        if [ ! -f "enterprise/types/features.ts" ]; then
          echo "❌ 企业版功能定义不存在！"
          exit 1
        fi
        echo "✅ 企业版代码验证通过"

    - name: Log in to Private Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.PRIVATE_REGISTRY }}
        username: ${{ secrets.PRIVATE_REGISTRY_USERNAME }}
        password: ${{ secrets.PRIVATE_REGISTRY_PASSWORD }}

    - name: Extract metadata for Enterprise Edition
      id: meta-enterprise
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.PRIVATE_REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=semver,pattern={{version}}-enterprise
          type=semver,pattern={{major}}.{{minor}}-enterprise
          type=raw,value=enterprise-latest,enable={{is_default_branch}}

    - name: Build and push Enterprise Edition
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.enterprise
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta-enterprise.outputs.tags }}
        labels: ${{ steps.meta-enterprise.outputs.labels }}
        cache-from: |
          type=gha
          type=registry,ref=${{ secrets.PRIVATE_REGISTRY }}/${{ env.IMAGE_NAME }}:enterprise-buildcache
        cache-to: |
          type=gha,mode=max
          type=registry,ref=${{ secrets.PRIVATE_REGISTRY }}/${{ env.IMAGE_NAME }}:enterprise-buildcache,mode=max
        build-args: |
          BUILDKIT_INLINE_CACHE=1
          MISONOTE_EDITION=enterprise

    - name: Generate usage documentation
      if: github.event_name != 'pull_request'
      run: |
        cat > DOCKER-USAGE.md << 'EOF'
        # 🐳 Docker 镜像使用说明

        ## 📦 预构建镜像

        我们提供了预构建的 Docker 镜像，支持多种架构：

        - **AMD64** (x86_64) - 适用于大多数服务器和桌面环境
        - **ARM64** (aarch64) - 适用于 Apple Silicon Mac、树莓派等

        ## 🚀 快速开始

        ### 1. 直接运行

        ```bash
        # 使用默认临时密码 (admin123)
        docker run -d -p 3001:3001 --name misonote-markdown ${{ secrets.DOCKER_USERNAME }}/misonote-markdown:latest

        # 启动时设置自定义密码（推荐）
        docker run -d \
          -p 3001:3001 \
          -e ADMIN_PASSWORD=admin123 \
          --name misonote-markdown \
          ${{ secrets.DOCKER_USERNAME }}/misonote-markdown:latest

        # 使用特定版本
        docker run -d \
          -p 3001:3001 \
          -e ADMIN_PASSWORD=admin123 \
          --name misonote-markdown \
          ${{ secrets.DOCKER_USERNAME }}/misonote-markdown:v1.0.0
        ```

        ### 2. 使用 Docker Compose

        创建 `docker-compose.yml` 文件：

        ```yaml
        services:
          misonote-markdown:
            image: ${{ secrets.DOCKER_USERNAME }}/misonote-markdown:latest
            container_name: misonote-markdown
            ports:
              - "3001:3001"
            volumes:
              - ./docs:/app/docs
              - ./data:/app/data
              - ./logs:/app/logs
            environment:
              - NODE_ENV=production
              # 设置管理员密码（推荐修改）
              - ADMIN_PASSWORD=admin123
            restart: unless-stopped
        ```

        ### 3. 环境变量配置

        | 变量名 | 描述 | 默认值 |
        |--------|------|--------|
        | `NODE_ENV` | 运行环境 | `production` |
        | `PORT` | 服务端口 | `3001` |
        | `ADMIN_PASSWORD` | 管理员密码（明文，启动时自动加密） | `admin123` |
        | `ADMIN_PASSWORD_HASH_BASE64` | 管理员密码哈希 | 自动生成 |
        | `JWT_SECRET` | JWT 密钥 | 自动生成 |
        | `MCP_API_KEY` | MCP 客户端 API 密钥 | 自动生成 |

        ### 4. 健康检查

        ```bash
        curl http://localhost:3001/api/health
        ```

        ## 📋 可用标签

        - `latest` - 最新稳定版本
        - `v1.0.0` - 特定版本
        - `main` - 主分支最新版本

        ## 🔗 链接

        - [Docker Hub](https://hub.docker.com/r/${{ secrets.DOCKER_USERNAME }}/misonote-markdown)
        - [GitHub Repository](https://github.com/${{ github.repository }})
        EOF

    - name: Upload usage documentation
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: docker-usage-docs
        path: DOCKER-USAGE.md
